2021-04-10 14:19:22.528 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:19:22.536 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:19:22.770 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 14:19:22.777 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 14:19:22.840 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:19:22.841 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:19:22.843 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:19:22.846 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 14:19:22.862 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 14:19:22.863 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:19:22.970 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:19:22.970 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 14:19:22.973 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:19:22.976 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(plugin_name)
    │       │            └ 'salmon/plugins/botmanage'
    │       └ <function load_plugins at 0x0000015C40ACDCA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/plugins/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x0000015C63D625E0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x0000015C63135CC0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000015C6312A7F0>, origin='salmon/pl...
             └ <function _load at 0x0000015C3DABF040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/plugins/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(bot: Bot, event: CQEvent):
                                 │           └ <class 'nonebot.adapters.cqhttp.event.Event'>
                                 └ <class 'nonebot.adapters.cqhttp.bot.Bot'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:19:22.986 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:19:22.990 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:19:22.992 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:19:22.993 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:19:23.026 | INFO     | uvicorn:serve:405 - Started server process [2040]
2021-04-10 14:19:23.026 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:19:23.029 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:19:23.029 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:19:23.029 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:19:24.984 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 59279) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:19:24.985 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 14:20:07.377 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:20:08.009 | INFO     | news:news_poller:86 - 台服官网新闻缓存为空，已加载至最新
2021-04-10 14:20:08.094 | INFO     | news:news_poller:86 - B服官网新闻缓存为空，已加载至最新
2021-04-10 14:20:08.094 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:20:25.000 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:20:25.429 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:20:25.432 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:25:15.035 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:25:15.632 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:25:15.710 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:25:15.710 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:25:25.001 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:25:25.318 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:25:25.321 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:30:10.452 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:30:10.997 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:30:11.069 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:30:11.069 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:30:25.001 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:30:25.418 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:30:25.420 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:30:47.461 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:30:47.462 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:30:47.631 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 14:30:47.633 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 14:30:47.685 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:30:47.686 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:30:47.687 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:30:47.690 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 14:30:47.693 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 14:30:47.694 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:30:47.752 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:30:47.753 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 14:30:47.754 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:30:47.758 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(plugin_name)
    │       │            └ 'salmon/plugins/botmanage'
    │       └ <function load_plugins at 0x000002604770ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/plugins/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002606A9A75E0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x0000026069D791C0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000026069D68550>, origin='salmon/pl...
             └ <function _load at 0x00000260446CF040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/plugins/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(event: NoticeEvent):
                                   └ <class 'nonebot.adapters.cqhttp.event.NoticeEvent'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:30:47.773 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:30:47.775 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:30:47.778 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:30:47.778 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:30:47.805 | INFO     | uvicorn:serve:405 - Started server process [3728]
2021-04-10 14:30:47.805 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:30:47.807 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:30:47.807 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:30:47.808 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:30:49.971 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 59573) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:30:49.972 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 14:32:45.071 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:32:45.072 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:32:45.158 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(plugin_name)
    │       │            └ 'salmon/plugins/botmanage'
    │       └ <function load_plugins at 0x000001D39A62DCA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/plugins/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000001D3BCADC4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x000001D3BCC95D00>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000001D3BCC94280>, origin='salmon/pl...
             └ <function _load at 0x000001D3975EF040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/plugins/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(event: CQEvent):
                                   └ <class 'nonebot.adapters.cqhttp.event.Event'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:32:45.167 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:32:45.175 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:32:45.185 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:32:45.311 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 14:32:45.313 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 14:32:45.366 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:32:45.367 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:32:45.368 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:32:45.370 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 14:32:45.374 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 14:32:45.374 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:32:45.430 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:32:45.431 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 14:32:45.433 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:32:45.433 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:32:45.452 | INFO     | uvicorn:serve:405 - Started server process [10372]
2021-04-10 14:32:45.452 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:32:45.453 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:32:45.454 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:32:45.454 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:32:47.970 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 59630) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:32:47.970 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 14:35:16.164 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:35:16.800 | INFO     | news:news_poller:86 - 台服官网新闻缓存为空，已加载至最新
2021-04-10 14:35:16.856 | INFO     | news:news_poller:86 - B服官网新闻缓存为空，已加载至最新
2021-04-10 14:35:16.856 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:35:25.006 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:35:25.421 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:35:25.423 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:40:19.601 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:40:20.369 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:40:20.461 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:40:20.461 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:40:25.006 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:40:25.312 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:40:25.314 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:45:02.982 | INFO     | salmon:wrapper:15 - Scheduled job pcr_reminder_tw start.
2021-04-10 14:45:02.984 | INFO     | salmon:wrapper:17 - Scheduled job pcr_reminder_tw completed.
2021-04-10 14:45:03.188 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:45:03.871 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:45:03.952 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:45:03.953 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:45:25.000 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:45:25.319 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:45:25.321 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:50:18.041 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:50:18.597 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:50:18.673 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:50:18.673 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:50:25.000 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:50:25.298 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:50:25.300 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:55:16.605 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 14:55:17.292 | INFO     | news:news_poller:90 - 未检索到台服官网新闻更新
2021-04-10 14:55:17.364 | INFO     | news:news_poller:90 - 未检索到B服官网新闻更新
2021-04-10 14:55:17.364 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 14:55:25.002 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 14:55:25.419 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 14:55:25.420 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 14:55:55.108 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:55:55.109 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:56:22.849 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:56:22.851 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:56:22.997 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "arena"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/priconne'
    │       └ <function load_plugins at 0x000002671317ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/priconne'), name='arena', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002673562C4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x00000267357E6E00>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='arena', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000267357E4280>, origin='salmon/mo...
             └ <function _load at 0x000002671013F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/priconne\arena.py", line 10, in <module>
    from salmon.plugins.priconne.pcr_data import chara
         └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

ModuleNotFoundError: No module named 'salmon.plugins'
2021-04-10 14:56:23.095 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:56:23.097 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:56:23.098 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:56:23.099 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "gacha"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/priconne'
    │       └ <function load_plugins at 0x000002671317ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/priconne'), name='gacha', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002673562C4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x0000026731F7EBC0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='gacha', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000026731F96D30>, origin='salmon/mo...
             └ <function _load at 0x000002671013F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/priconne\gacha.py", line 9, in <module>
    from salmon.plugins.priconne.pcr_data import chara
         └ <module 'salmon' from 'C:\\bot\\SalmonBot\\salmon\\__init__.py'>

ModuleNotFoundError: No module named 'salmon.plugins'
2021-04-10 14:56:23.105 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "games"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/priconne'
    │       └ <function load_plugins at 0x000002671317ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/priconne'), name='games', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002673562C4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x00000267357E6E00>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='games', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000026731F81F40>, origin='salmon/mo...
             └ <function _load at 0x000002671013F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/priconne\games.py", line 7, in <module>
    from salmon.plugins.priconne.pcr_data import _pcr_data, chara

ModuleNotFoundError: No module named 'salmon.plugins'
2021-04-10 14:56:23.108 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:56:23.168 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:56:23.169 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "pool"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/priconne'
    │       └ <function load_plugins at 0x000002671317ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/priconne'), name='pool', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002673562C4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x0000026731F7EBC0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='pool', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000026731FE9790>, origin='salmon/mod...
             └ <function _load at 0x000002671013F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/priconne\pool.py", line 3, in <module>
    from salmon.plugins.priconne.pcr_data import chara

ModuleNotFoundError: No module named 'salmon.plugins'
2021-04-10 14:56:23.173 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:56:23.176 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x000002671317ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x0000026735EDFC10>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x00000267357DFD80>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000026735EE1430>, origin='salmon/mo...
             └ <function _load at 0x000002671013F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(bot: Bot, event: CQEvent):
                                 │           └ <class 'nonebot.adapters.cqhttp.event.Event'>
                                 └ <class 'nonebot.adapters.cqhttp.bot.Bot'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:56:23.214 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:56:23.214 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:56:23.216 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:56:23.216 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:56:23.236 | INFO     | uvicorn:serve:405 - Started server process [9260]
2021-04-10 14:56:23.237 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:56:23.238 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:56:23.238 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:56:23.239 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:56:25.989 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60406) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:56:25.990 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 14:58:41.719 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:58:41.720 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:58:41.803 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x0000022BF4EEECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x0000022B9739C4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x0000022B97554C00>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x0000022B97555280>, origin='salmon/mo...
             └ <function _load at 0x0000022BF222F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(bot: Bot, event: CQEvent):
                                 │           └ <class 'nonebot.adapters.cqhttp.event.Event'>
                                 └ <class 'nonebot.adapters.cqhttp.bot.Bot'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:58:41.810 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:58:41.811 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:58:41.814 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:58:41.915 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 14:58:41.917 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 14:58:41.971 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:58:41.972 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:58:41.973 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:58:41.982 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 14:58:41.988 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 14:58:41.989 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:58:42.044 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:58:42.045 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 14:58:42.047 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:58:42.047 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:58:42.065 | INFO     | uvicorn:serve:405 - Started server process [15144]
2021-04-10 14:58:42.065 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:58:42.067 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:58:42.067 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:58:42.067 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:58:43.978 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60474) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:58:43.978 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 14:59:20.318 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 14:59:20.320 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 14:59:20.509 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 14:59:20.511 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 14:59:20.572 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 14:59:20.574 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 14:59:20.575 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 14:59:20.577 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 14:59:20.580 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 14:59:20.581 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 14:59:20.638 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 14:59:20.639 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 14:59:20.640 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 14:59:20.644 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x000001C35A05ECA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000001C37D2F25E0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x000001C37C6CA040>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000001C37C6B8550>, origin='salmon/mo...
             └ <function _load at 0x000001C35701F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(event):

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 14:59:20.659 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 14:59:20.660 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 14:59:20.663 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 14:59:20.663 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 14:59:20.699 | INFO     | uvicorn:serve:405 - Started server process [4808]
2021-04-10 14:59:20.699 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 14:59:20.701 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 14:59:20.702 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 14:59:20.702 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 14:59:20.969 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60485) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 14:59:20.970 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 15:00:07.363 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 15:00:07.952 | INFO     | news:news_poller:86 - 台服官网新闻缓存为空，已加载至最新
2021-04-10 15:00:08.060 | INFO     | news:news_poller:86 - B服官网新闻缓存为空，已加载至最新
2021-04-10 15:00:08.061 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 15:00:25.001 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 15:00:26.596 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 15:00:26.598 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 15:02:47.310 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 15:02:47.312 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 15:02:47.481 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 15:02:47.483 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 15:02:47.536 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 15:02:47.537 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 15:02:47.538 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 15:02:47.541 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 15:02:47.545 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 15:02:47.546 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 15:02:47.602 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 15:02:47.603 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 15:02:47.605 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 15:02:47.608 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x000001ED2B2ADCA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000001ED4E293EE0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x000001ED4D917800>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000001ED289B7F10>, origin='salmon/mo...
             └ <function _load at 0x000001ED285CF040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(bot: Bot, event: CQEvent):
                                 │           └ <class 'nonebot.adapters.cqhttp.event.Event'>
                                 └ <class 'nonebot.adapters.cqhttp.bot.Bot'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 15:02:47.614 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 15:02:47.615 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 15:02:47.617 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 15:02:47.617 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 15:02:47.636 | INFO     | uvicorn:serve:405 - Started server process [15888]
2021-04-10 15:02:47.636 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 15:02:47.637 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 15:02:47.638 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 15:02:47.638 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 15:02:47.972 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60571) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 15:02:47.973 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 15:04:20.669 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 15:04:20.671 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 15:04:20.768 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x000002874103CCA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x00000287634EC4C0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x00000287636A5C40>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x00000287636A4280>, origin='salmon/mo...
             └ <function _load at 0x000002873E36F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert():

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 15:04:20.774 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 15:04:20.775 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 15:04:20.776 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 15:04:20.862 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 15:04:20.864 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 15:04:20.917 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 15:04:20.918 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 15:04:20.919 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 15:04:20.922 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 15:04:20.926 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 15:04:20.928 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 15:04:21.027 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 15:04:21.029 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 15:04:21.032 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 15:04:21.032 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 15:04:21.050 | INFO     | uvicorn:serve:405 - Started server process [10532]
2021-04-10 15:04:21.050 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 15:04:21.052 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 15:04:21.052 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 15:04:21.052 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 15:04:21.971 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60606) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 15:04:21.971 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
2021-04-10 15:05:15.150 | INFO     | salmon:wrapper:15 - Scheduled job pcr_news_poller start.
2021-04-10 15:05:15.773 | INFO     | news:news_poller:86 - 台服官网新闻缓存为空，已加载至最新
2021-04-10 15:05:15.853 | INFO     | news:news_poller:86 - B服官网新闻缓存为空，已加载至最新
2021-04-10 15:05:15.854 | INFO     | salmon:wrapper:17 - Scheduled job pcr_news_poller completed.
2021-04-10 15:05:25.004 | INFO     | salmon:wrapper:15 - Scheduled job update_seeker start.
2021-04-10 15:05:25.490 | INFO     | comic:update_seeker:120 - 未检测到官漫更新
2021-04-10 15:05:25.492 | INFO     | salmon:wrapper:17 - Scheduled job update_seeker completed.
2021-04-10 15:06:57.426 | INFO     | nonebot:init:174 - NoneBot is initializing...
2021-04-10 15:06:57.428 | INFO     | nonebot:init:176 - Current Env: dev
2021-04-10 15:06:57.593 | WARNING  | arena:<module>:40 - arena_db.json not found, will create when needed.
2021-04-10 15:06:57.596 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena"
2021-04-10 15:06:57.647 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "arena_reminder"
2021-04-10 15:06:57.648 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "cherugo"
2021-04-10 15:06:57.649 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "comic"
2021-04-10 15:06:57.652 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "gacha"
2021-04-10 15:06:57.656 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "games"
2021-04-10 15:06:57.657 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "login_bonus"
2021-04-10 15:06:57.713 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "news"
2021-04-10 15:06:57.714 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "pool"
2021-04-10 15:06:57.716 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "query"
2021-04-10 15:06:57.720 | ERROR    | nonebot:_load_plugin:1037 - Failed to import "alert"
Traceback (most recent call last):

  File "C:\bot\SalmonBot\run.py", line 15, in <module>
    nonebot.load_plugins(module_name)
    │       │            └ 'salmon/modules/botmanage'
    │       └ <function load_plugins at 0x000002C17888DCA0>
    └ <module 'nonebot' from 'C:\\Users\\WatanabeAsa\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\nonebot\\__in...

  File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1044, in load_plugins
    result = context.run(_load_plugin, module_info)
             │       │   │             └ ModuleInfo(module_finder=FileFinder('salmon/modules/botmanage'), name='alert', ispkg=False)
             │       │   └ <function load_plugins.<locals>._load_plugin at 0x000002C11BC705E0>
             │       └ <method 'run' of 'Context' objects>
             └ <Context object at 0x000002C11AEF5CC0>

> File "C:\Users\WatanabeAsa\AppData\Local\Programs\Python\Python39\lib\site-packages\nonebot\plugin.py", line 1028, in _load_plugin
    module = _load(spec)
             │     └ ModuleSpec(name='alert', loader=<_frozen_importlib_external.SourceFileLoader object at 0x000002C11AEE8880>, origin='salmon/mo...
             └ <function _load at 0x000002C17585F040>

  File "<frozen importlib._bootstrap>", line 711, in _load
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed

  File "salmon/modules/botmanage\alert.py", line 7, in <module>
    async def kick_me_alert(bot: Bot, event: CQEvent):
                                 │           └ <class 'nonebot.adapters.cqhttp.event.Event'>
                                 └ <class 'nonebot.adapters.cqhttp.bot.Bot'>

TypeError: __init__() takes 1 positional argument but 2 were given
2021-04-10 15:06:57.733 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "broadcast"
2021-04-10 15:06:57.734 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "help"
2021-04-10 15:06:57.735 | INFO     | nonebot:_load_plugin:1034 - Succeeded to import "service_manage"
2021-04-10 15:06:57.735 | INFO     | nonebot:run:218 - Running NoneBot...
2021-04-10 15:06:57.753 | INFO     | uvicorn:serve:405 - Started server process [4400]
2021-04-10 15:06:57.754 | INFO     | uvicorn:startup:22 - Waiting for application startup.
2021-04-10 15:06:57.755 | INFO     | nonebot_plugin_apscheduler:_start_scheduler:21 - Scheduler Started
2021-04-10 15:06:57.755 | INFO     | uvicorn:startup:34 - Application startup complete.
2021-04-10 15:06:57.756 | INFO     | uvicorn:startup:492 - Uvicorn running on http://127.0.0.1:8080 (Press CTRL+C to quit)
2021-04-10 15:06:59.969 | INFO     | uvicorn:asgi_send:182 - ('127.0.0.1', 60656) - "WebSocket /cqhttp/ws" [accepted]
2021-04-10 15:06:59.970 | INFO     | nonebot:_handle_ws_reverse:234 - WebSocket Connection from CQHTTP Bot 3235657949 Accepted!
